# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0eb70e5333b3df1460afb5f3b7c9aefe03476820a3ca798e9dc9aa3f81081619248a1b83ff385eb21eb9c4f41b523decaec77eb7a1f3a275cd418dc7cee21fc6

test:
  secret_key_base: d98e3ae05cd7dda65b94f3358af6a6667508f8e1b247b72f46d479f4713e2502667ea36b84d42f059bdf45134f16a3d7691866c89cf63699afd79c6379252260

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
